apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaiburr-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaiburr-app
  template:
    metadata:
      labels:
        app: kaiburr-app
    spec:
      # This tells the pod to use the identity with permissions from rbac.yaml
      serviceAccountName: task-executor-sa
      containers:
      - name: kaiburr-app
        # IMPORTANT: Change this to your Docker Hub username and image name
        image: your-docker-username/kaiburr-task-app:latest
        imagePullPolicy: IfNotPresent # Use this if you loaded the image locally to minikube
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI # This environment variable will override application.properties
          valueFrom:
            secretKeyRef:
              name: mongo-secret # The name of the Secret to use
              key: MONGO_URI    # The key within the Secret to get the value from