# disable Spring AI MongoDB vector-store auto-config (you don't need AI for Task1)
spring.autoconfigure.exclude=org.springframework.ai.autoconfigure.vectorstore.mongodb.MongoDBAtlasVectorStoreAutoConfiguration

# MongoDB connection
spring.data.mongodb.uri=mongodb://localhost:27017/kaiburr

# Server port
server.port=8080

# Show SQL/logs (optional)
logging.level.org.springframework=INFO
